### PR TITLE
Add mkl

### PR DESCRIPTION
**Pull request by schmoelder**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I'm actually still a bit confused about some other things with conda-forge so I created a post in their forum: https://conda.discourse.group/t/help-with-build-variants/664

### CODE REVIEW

**Comment by schmoelder** [comment]
@conda-forge-admin, please rerender

**Comment by schmoelder** [comment]
@conda-forge-admin, please rerender

**Comment by schmoelder** [comment]
@conda-forge-admin, please rerender

**Comment by schmoelder** [comment]
@conda-forge-admin, please rerender

**Comment by schmoelder** [comment]
@jbreue16, @sleweke, seems to me like it worked. Wanna have another look?

**Comment by schmoelder** [comment]
@conda-forge-admin, please rerender

**Comment by sleweke-bayer** [comment]
Stating the obvious, there's a missing symbol when running the test `cadet-cli --version` (compilation is fine):
```
dyld[8702]: symbol not found in flat namespace (_mkl_blas_caxpy)
```
On Linux, we have
```
   INFO (cadet,lib/libcadet.so.4.4.0): Needed DSO lib/libmkl_intel_lp64.so.2 found in conda-forge/linux-64::mkl==2023.2.0=h84fe81f_50496
   INFO (cadet,lib/libcadet.so.4.4.0): Needed DSO lib/libmkl_sequential.so.2 found in conda-forge/linux-64::mkl==2023.2.0=h84fe81f_50496
   INFO (cadet,lib/libcadet.so.4.4.0): Needed DSO lib/libmkl_core.so.2 found in conda-forge/linux-64::mkl==2023.2.0=h84fe81f_50496
```
but on OSX, we only get
```
   INFO (cadet,lib/libcadet.4.4.0.dylib): Needed DSO lib/libmkl_intel_lp64.2.dylib found in conda-forge/osx-64::mkl==2023.2.0=h54c2260_50500
```

It would help to know in which lib this symbol is defined.

**Comment by schmoelder** [comment]
@ronald-jaepel found out that there is actually no need to include this during build time. Users can freely choose their blas implementation during install / run time. For more information, refer to: https://conda-forge.org/docs/maintainer/knowledge_base/#blas

**Pull request closed without merging**
